### ISSUE TITLE
[FEATURE] Set up new services for deployment

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#487]
## Tasks:
- [x] Set up reverse proxy for `/v2` (refer `nginx.conf` in web)
- [x] Add python api Dockerfile (refer Dockerfile in api, do not implement stages for now)
- [x] Load certificates in python api (refer golang api or [hubconf api](https://github.com/AUBGTheHUB/hub-conf-signup/blob/097ad0d8bbb6b0cfd1013ed6a322ee257cd5a02a/packages/api/server.js#L73)) <-- prioritize this now
- [x] Add python api in compose with shared volume for logs (refer `docker-compose.yaml` in root)
- [x] Add health check for python api and url shortener in `manage_app.py` (refer `manage_app.py`)
- [x] (OPTIONAL) Update `manage_app.py` to accept new flags for enabling easier debugging locally
```bash
./manage_app.py --no-health-checks --no-cd --no-renewal
```

 `--no-health-checks` disables all health checks
 `--no-cd` disables checking for newer changes
 `--no-renewal` disables the renewal of certificates, enables developers to use self signed certificates 
- [ ] (OPTIONAL) Set up a sandbox for testing the `manage_app.py`. A container which runs the script within itself, sets up all needed certificates and binds all needed ports for enabling local testing. Project's root is a shared volume.
- Loads the environment from the globally shared `.env`, there won't be any need to overwrite our config files manually.
- It will enable for easier testing of the certs installation/rotation and ssl configurations.

**Comment by IvanObreshkov** [comment]
Can I take this one?

**Comment by asynchroza** [comment]
> @asynchroza Can I take this one?
> 
> 

@IvanObreshkov fix the logging issue first.

**Comment by asynchroza** [comment]
@IvanObreshkov let's prioritize this one instead of #495.

**Comment by IvanObreshkov** [comment]
> @IvanObreshkov let's prioritize this one instead of #495.

Ok I will try to finish this one by 09/04/2023 (Monday)

**Comment by asynchroza** [comment]
@IvanObreshkov I will look into setting up the last optional task tonight in order to enable you to iterate faster by not needing to set up all of the environment by yourself.

**Comment by asynchroza** [comment]
> @IvanObreshkov I will look into setting up the last optional task tonight in order to enable you to iterate faster by not needing to set up all of the environment by yourself.

@IvanObreshkov I decided to drop the ticket since it turned out to be a really complex one and the wins from it won't be substantial. You may still implement some flags to disable certain features in the manage_app.py script.
Refer to: https://github.com/AUBGTheHUB/monolith/blob/ddad72a1276461397fa8f507c757a39d1d30385c/manage_app.py#L23

**Comment by asynchroza** [comment]
##@IvanObreshkov Let's work on setting up the questionnaire for deployment as well. It needs to be reversed proxied on `/questionnaire`. 

https://kit.svelte.dev/docs/adapter-node

**Comment by asynchroza** [comment]
@IvanObreshkov Questionnaire service has been set to work with docker-compose. We need to set up the reverse proxy now.

- [ ] We need to install SSL certificates
- [ ] We need to set up reverse proxy `/questionnaires`
